site:
  title: IsyFact (Sonderzeichen - Local)
  url: https://isyfact.github.io/
  start_page: sonderzeichen::konzept.adoc
urls:
  latest_version_segment: current
  latest_prerelease_version_segment: dev
content:
  branches: []
  # Comment: Configuration for development (e.g. with feature branches that aren't pushed yet)
  # Convention: All git repositories are cloned in the same parent directory.
  sources:
    - url: ../isy-documentation
      branches: [master]
      start_path: glossary
      version:
        'master': 'latest'
    - url: ../isy-sonderzeichen
      branches: [HEAD, develop]
      start_path: docs
      version:
        'feature/(*)': $1
        'release/(*)': $1
        'develop': 'next'
        '(*)': $1
#    - url: ../isy-sonderzeichen
#      tags: 4.0.0
#      start_path: isy-sonderzeichen-doc
#      version: 4.0.0
runtime:
  fetch: true
  log:
    level: info
    failure_level: fatal
asciidoc:
  attributes:
    page-component-order: 'sonderzeichen, *, glossary'
    page-toctitle: Inhalt
    sectnums: true
    sectnumlevels: 5
    caution-caption: Achtung
    important-caption: Wichtig
    note-caption: Hinweis
    tip-caption: Tipp
    warning-caption: Warnung
    appendix-caption: Anhang
    example-caption: Beispiel
    figure-caption: Abbildung
    table-caption: Tabelle
    listing-caption: Listing
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en, de]
