name: "dump-environment"
description: "Dump Runners Environment"

runs:
  using: "composite"
  
  steps:
    - name: Composite 'Runners environment'
      shell: bash
      run: |
        FOLDER_PWD="$(pwd)"
        
        echo "-- Start environment dump ------------------"
        echo ""
        echo "Content of folder >$FOLDER_PWD<"
        ls -la
        echo ""
        echo "Content of folder >$FOLDER_PWD/target<"
        ls -la $FOLDER_PWD/target
        echo ""
        echo "-- Environment dump finished----------------"  
