name: Auto-Changelog for Dependabot Pull Requests

on:
  pull_request_target:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  version:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/next_version.yml@v2.1.1
    with:
      next-version: 5.0.0

  changelog:
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dangoslen/dependabot-changelog-helper@v4
        with:
          activationLabels: dependencies
          changelogPath: './CHANGELOG.md'
          dependencyTool: dependabot
          version: ${{ needs.Version.outputs.next-version }}
          sectionHeader: /^### [(dependency upgrades|DEPENDENCY UPGRADES)]

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: adds changelog entry after upgrading dependency version"